# https://lgtm.com/docs/lgtm/lgtm.yml-configuration-file
path_classifiers:
    test:
        - "*/*/test_*.cpp"
    docs:
        - README.md
        - LICENSE.txt
    library:
        - boost
        - cryptopp
        - googletest
        - hunspell
        - openssl

extraction:
    cpp:
        prepare:
            packages:
                - g++-10
                - pkg-config
                - python3
                - unzip
                - zip
                - zlib1g-dev
        after_prepare:
            - npm install -g @bazel/bazelisk
            - mkdir -p $LGTM_WORKSPACE/latest-gcc-symlinks
            - ln -s /usr/bin/g++-10 $LGTM_WORKSPACE/latest-gcc-symlinks/g++
            - ln -s /usr/bin/gcc-10 $LGTM_WORKSPACE/latest-gcc-symlinks/gcc
            - export PATH=$LGTM_WORKSPACE/latest-gcc-symlinks:$PATH:$HOME/bin
            - export AR=gcc-ar-10
            - export RANLIB=gcc-ranlib-10
            - export GNU_MAKE=make
            - export GIT=true
            - export BAZEL=bazelisk
            - export BOOST_DIR=$LGTM_SRC/boost
            - export GTEST_DIR=$LGTM_SRC/googletest
            - export HUNSPELL_DIR=$LGTM_SRC/hunspell
            - export CRYPTOPP_DIR=$LGTM_SRC/cryptopp
            - export OPENSSL_DIR=$LGTM_SRC/openssl
        configure:
            command:
                - ./prepare_deps
        index:
            build_command:
                - $GNU_MAKE -k
